name: Working with env and secrt variables

on: push

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: hamzaumer
  IMAGE_NAME: github-actions-nginx

jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: echo docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME

      - name: Docker Login
        env:
          DOCKER_PASSWORD: Hamz@7890
        run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

      - name: Docker Publish
        run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy: 
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Docker run
        run: echo run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

