name: Multi jobs workflow

on: push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
    - name: Install cowsay libraray
      run: sudo apt-get install cowsay -y

    - name: Execute cowsay art work
      run: cowsay -f dragon "Run for cover I am dragon ................rawwww!" >> dragon.txt
    
    - name: sleep f0r 30 seconds
      run: sleep 30

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      

      - name: Test "Check file exsits"
        run: grep -i "dragon" dragon.txt
      

  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
      - name: Display Ascii Art work
        run: cat dragon.txt

      - name: Display Message
        run: echo "Deploying........."
