name: My first work flow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v6

        - name: Welcome Message
          run: ls -ltra
                

        - name: Executing shell file
          run: |
              chmod +x ./ascii.sh
              ./ascii.sh


        # - name: list file
        #   run: ls

        # - name: read file
        #   run: cat README.md






