name: My first work flow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v6

        - name: Welcome Message
          run: |
                echo "My first work flow"
                ls -ltr
                cat README.md

        - name: Genrate art work
          run: |
              sudo apt install cowsay 
              cowsay -f dragon "Run for cover I am dragon ................rawwww!" >> dragon.txt


        # - name: list file
        #   run: ls

        # - name: read file
        #   run: cat README.md






